version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_HOST=0.0.0.0
      - API_PORT=3000
      - DEBUG=True
    depends_on:
      - db
    command: sh -c "python qrcode_generator.py"
    networks:
      - qr-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - qr-network
    restart: unless-stopped

  mysql-backup:
    image: mysql:8
    container_name: mysql-backup
    volumes:
      - ./backups:/backups
      - mysql_data:/var/lib/mysql:ro
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    entrypoint: []
    command: >
      sh -c '
      while true; do
        echo "Starting backup process at $(date)"
        TIMESTAMP=$$(date +%Y%m%d-%H%M)
        BACKUP_FILE="${DB_NAME}_$${TIMESTAMP}.sql.gz"
        echo "Creating MySQL backup..."
        if mysqldump -h "${DB_HOST}" -u "${DB_USER}" -p"${DB_PASSWORD}" "${DB_NAME}" | gzip > "/backups/$${BACKUP_FILE}"; then
          echo "Backup created successfully: $${BACKUP_FILE}"
          echo "Cleaning up old backups..."
          ls -t /backups/${DB_NAME}_*.sql.gz | tail -n +8 | xargs -r rm
          echo "Backup process completed successfully at $(date)"
        else
          echo "Error: Failed to create backup"
        fi
        sleep 300
      done'
    networks:
      - qr-network
    depends_on:
      - db

networks:
  qr-network:
    driver: bridge

volumes:
  mysql_data:
    name: qr_mysql_data
    driver: local
