version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_HOST=0.0.0.0
<<<<<<< HEAD
      - API_PORT=3000
      - DEBUG=True
=======
      - API_PORT=${API_PORT:-3000}
      - DEBUG=${DEBUG:-False}
>>>>>>> 09d1517 (Enhance docker-compose.yml with resource limits and default values for environment variables, improving memory management and flexibility across environments.)
    depends_on:
      - db
    command: sh -c "python qrcode_generator.py"
    networks:
      - qr-network
    container_name: qr-api-${ENVIRONMENT:-production}
    deploy:
      resources:
        limits:
          memory: 128M

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - qr-network
    restart: unless-stopped
    container_name: qr-db-${ENVIRONMENT:-production}
    deploy:
      resources:
        limits:
          memory: 256M

  mysql-backup:
    image: alpine:latest
    container_name: mysql-backup
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
      - mysql_data:/var/lib/mysql:ro
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: sh -c "while true; do sleep 3600; /scripts/backup.sh; done"
    networks:
      - qr-network
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 64M

networks:
  qr-network:
    name: qr-network-${ENVIRONMENT:-production}
    driver: bridge

volumes:
  mysql_data:
    name: qr_mysql_data_${ENVIRONMENT:-production}
    driver: local
