# Usa una imagen base de Python
FROM python:3.12-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de tu aplicación al contenedor
COPY . /app

# Instala las dependencias
RUN pip install -r requirements.txt

# Expone el puerto en el que la aplicación Flask escucha
EXPOSE 5000

# Define el comando para ejecutar la aplicación
CMD ["python", "qrcode_reader.py"]